/* Message numbers (RFC 4250 section 4.1) and related constants. */
#ifndef TUNNEL_SSH_MSG_H
#define TUNNEL_SSH_MSG_H

enum {
	/* transport, RFC 4253 */
	SSH_MSG_DISCONNECT = 1,
	SSH_MSG_IGNORE = 2,
	SSH_MSG_UNIMPLEMENTED = 3,
	SSH_MSG_DEBUG = 4,
	SSH_MSG_SERVICE_REQUEST = 5,
	SSH_MSG_SERVICE_ACCEPT = 6,
	SSH_MSG_EXT_INFO = 7,
	SSH_MSG_KEXINIT = 20,
	SSH_MSG_NEWKEYS = 21,
	SSH_MSG_KEX_ECDH_INIT = 30,
	SSH_MSG_KEX_ECDH_REPLY = 31,
	/* userauth, RFC 4252 */
	SSH_MSG_USERAUTH_REQUEST = 50,
	SSH_MSG_USERAUTH_FAILURE = 51,
	SSH_MSG_USERAUTH_SUCCESS = 52,
	SSH_MSG_USERAUTH_BANNER = 53,
	SSH_MSG_USERAUTH_PK_OK = 60,
	/* connection, RFC 4254 */
	SSH_MSG_GLOBAL_REQUEST = 80,
	SSH_MSG_REQUEST_SUCCESS = 81,
	SSH_MSG_REQUEST_FAILURE = 82,
	SSH_MSG_CHANNEL_OPEN = 90,
	SSH_MSG_CHANNEL_OPEN_CONFIRMATION = 91,
	SSH_MSG_CHANNEL_OPEN_FAILURE = 92,
	SSH_MSG_CHANNEL_WINDOW_ADJUST = 93,
	SSH_MSG_CHANNEL_DATA = 94,
	SSH_MSG_CHANNEL_EXTENDED_DATA = 95,
	SSH_MSG_CHANNEL_EOF = 96,
	SSH_MSG_CHANNEL_CLOSE = 97,
	SSH_MSG_CHANNEL_REQUEST = 98,
	SSH_MSG_CHANNEL_SUCCESS = 99,
	SSH_MSG_CHANNEL_FAILURE = 100,
};

enum {
	SSH_DISCONNECT_PROTOCOL_ERROR = 2,
	SSH_DISCONNECT_KEY_EXCHANGE_FAILED = 3,
	SSH_DISCONNECT_MAC_ERROR = 5,
	SSH_DISCONNECT_SERVICE_NOT_AVAILABLE = 7,
	SSH_DISCONNECT_HOST_KEY_NOT_VERIFIABLE = 9,
	SSH_DISCONNECT_BY_APPLICATION = 11,
	SSH_DISCONNECT_NO_MORE_AUTH_METHODS = 14,
};

enum {
	SSH_OPEN_ADMINISTRATIVELY_PROHIBITED = 1,
	SSH_OPEN_CONNECT_FAILED = 2,
	SSH_OPEN_UNKNOWN_CHANNEL_TYPE = 3,
	SSH_OPEN_RESOURCE_SHORTAGE = 4,
};

#define SSH_EXTENDED_DATA_STDERR 1

#endif
